import { Task } from '@/types';

export const TASKS: Task[] = [
  { id: 1, name: "Essuyer plans de travail", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 5 },
  { id: 2, name: "Nettoyer évier", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 5 },
  { id: 3, name: "Balayer/laver sol cuisine", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 10 },
  { id: 4, name: "Faire vaisselle", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 15 },
  { id: 5, name: "Vider poubelle", frequency: "quotidienne", zone: "Cuisine", estimatedTime: 3 },
  { id: 6, name: "Dépoussiérer surfaces visibles", frequency: "quotidienne", zone: "Salon", estimatedTime: 8 },
  { id: 7, name: "Aspirer/laver sol salon", frequency: "quotidienne", zone: "Salon", estimatedTime: 12 },
  { id: 8, name: "Ranger objets/coussins", frequency: "quotidienne", zone: "Salon", estimatedTime: 5 },
  { id: 9, name: "Nettoyer écrans TV/ordinateur", frequency: "quotidienne", zone: "Salon", estimatedTime: 5 },
  { id: 10, name: "Nettoyer lavabo", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 5 },
  { id: 11, name: "Désinfecter toilettes", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 8 },
  { id: 12, name: "Essuyer miroirs", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 3 },
  { id: 13, name: "Remplacer serviettes", frequency: "quotidienne", zone: "Salle de bain", estimatedTime: 3 },
  { id: 14, name: "Faire le lit", frequency: "quotidienne", zone: "Chambres", estimatedTime: 5 },
  { id: 15, name: "Ranger vêtements/objets", frequency: "quotidienne", zone: "Chambres", estimatedTime: 10 },
  { id: 16, name: "Aérer pièce", frequency: "quotidienne", zone: "Chambres", estimatedTime: 2 },
  { id: 17, name: "Aspirer sol chambres", frequency: "quotidienne", zone: "Chambres", estimatedTime: 10 },
  { id: 18, name: "Nettoyer micro-ondes intérieur", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 10 },
  { id: 19, name: "Nettoyer four", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 20 },
  { id: 20, name: "Dégraisser portes placard", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 15 },
  { id: 21, name: "Désinfecter frigo (tri périmés)", frequency: "hebdomadaire", zone: "Cuisine", estimatedTime: 15 },
  { id: 22, name: "Dépoussiérer meubles/objets", frequency: "hebdomadaire", zone: "Salon", estimatedTime: 20 },
  { id: 23, name: "Nettoyer fenêtres", frequency: "hebdomadaire", zone: "Salon", estimatedTime: 25 },
  { id: 24, name: "Aspirer tapis/canapés", frequency: "hebdomadaire", zone: "Salon", estimatedTime: 15 },
  { id: 25, name: "Nettoyer carreaux/joints", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 20 },
  { id: 26, name: "Désinfecter robinets/pommeau", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 10 },
  { id: 27, name: "Nettoyer brosses/accessoires", frequency: "hebdomadaire", zone: "Salle de bain", estimatedTime: 10 },
  { id: 28, name: "Changer draps/taies", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 15 },
  { id: 29, name: "Nettoyer sous lit/meubles", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 20 },
  { id: 30, name: "Ranger armoire/trier vêtements", frequency: "hebdomadaire", zone: "Chambres", estimatedTime: 30 },
  { id: 31, name: "Nettoyer hotte/grilles aération", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 25 },
  { id: 32, name: "Laver intérieur placards", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 40 },
  { id: 33, name: "Détartrer cafetière/bouilloire", frequency: "mensuelle", zone: "Cuisine", estimatedTime: 15 },
  { id: 34, name: "Laver rideaux/textiles", frequency: "mensuelle", zone: "Salon", estimatedTime: 30 },
  { id: 35, name: "Polir meubles bois", frequency: "mensuelle", zone: "Salon", estimatedTime: 25 },
  { id: 36, name: "Dépoussiérer luminaires", frequency: "mensuelle", zone: "Salon", estimatedTime: 20 },
  { id: 37, name: "Détartrer robinets/douche", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 20 },
  { id: 38, name: "Nettoyer évacuations eau", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 15 },
  { id: 39, name: "Laver tapis bain", frequency: "mensuelle", zone: "Salle de bain", estimatedTime: 10 },
  { id: 40, name: "Nettoyer matelas (aspiration)", frequency: "mensuelle", zone: "Chambres", estimatedTime: 20 },
  { id: 41, name: "Réorganiser tiroirs/étagères", frequency: "mensuelle", zone: "Chambres", estimatedTime: 35 },
  { id: 42, name: "Laver oreillers/couettes", frequency: "mensuelle", zone: "Chambres", estimatedTime: 30 },
  { id: 43, name: "Pyrolyser four", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 45 },
  { id: 44, name: "Nettoyer lave-vaisselle (vinaigre)", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 20 },
  { id: 45, name: "Nettoyer sous frigo/four", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 40 },
  { id: 46, name: "Récurer évier", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 15 },
  { id: 47, name: "Nettoyer portes placard int/ext", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 35 },
  { id: 48, name: "Désinfecter poubelle/compost", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 15 },
  { id: 49, name: "Lessiver murs/interrupteurs", frequency: "saisonnière", zone: "Cuisine", estimatedTime: 45 },
  { id: 50, name: "Laver housses coussins/canapé", frequency: "saisonnière", zone: "Salon", estimatedTime: 30 },
  { id: 100, name: "Faire carreaux", frequency: "trimestrielle", zone: "Sols", estimatedTime: 30 }
];

export const ZONES = [...new Set(TASKS.map(t => t.zone))];
